"""Add emailcolumn to EmailList

Revision ID: c02a0d8324ea
Revises: 
Create Date: 2025-01-17 10:58:51.433650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c02a0d8324ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emailcolumn', sa.String(length=100), nullable=False))
        batch_op.drop_column('name')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('emailcolumn')

    # ### end Alembic commands ###
